'use client';
import { Inter } from 'next/font/google';
import './globals.css';
import { Suspense } from 'react';

const inter = Inter({ subsets: ['latin'] });

const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang='en' data-theme='cupcake'>
            <head>
                <title>{metadata.title}</title>
                <meta name='description' content={metadata.description} />
                <link rel='icon' href='/favicon.ico' />
            </head>

            <body className={inter.className}>{children}</body>
        </html>
    );
}
